version: '3.7'
services:
  ft-nginx:
    container_name : ft-nginx
    image: nginx
    restart: always
    volumes:
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ftsocket:/tmp
    networks:
      - ftnet
    depends_on:
      - ft-web
    ports:
      - 9001:9001

  ft-web:
    container_name: ft-web
    image: ft-web
    build: .
    networks:
      - ftnet
    # ports:
    #   - 9000:9000
    # depends_on:
    #   - ft-db
    volumes:
      - ./:/var/www/Flask_Basic
      - ftsocket:/tmp
    restart: always
    environment:
      - FLASK_APP=Flask_Basic
      - FLASK_ENV=${FLASK_ENV:-development}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
    command: ['sh', './etc/docker-entrypoint.sh']

networks:
  ftnet:

volumes:
  ftvolume:
  ftsocket: