version: '3.7'
services:
  ft-web:
    container_name: ft-web
    image: ft-web
    build: .
    networks:
      - ftnet
    ports:
      - 9000:9000
    depends_on:
      - ft-db
    volumes:
      - ./:/var/www/Flask_Basic
    restart: always
    environment:
      - FLASK_APP=Flask_Basic
      - FLASK_ENV=${FLASK_ENV:-development}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
    command: ['sh', './etc/docker-entrypoint.sh']

  ft-db:
    container_name: ft-db
    image: mysql:5.7
    networks:
      - ftnet
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flask_basic
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    ports:
      - 3306:3306
    volumes:
      - ftvolume:/var/lib/mysql
    restart: always

networks:
  ftnet:

volumes:
  ftvolume: