"""Changed Memo table column name

Revision ID: 20239bfa99b0
Revises: a3e8054bdfee
Create Date: 2023-04-18 14:18:40.784870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20239bfa99b0'
down_revision = 'a3e8054bdfee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('upgraded_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('create_at')
        batch_op.drop_column('upgrade_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upgrade_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('create_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('upgraded_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
